version: '3.8'
services:
  crypton:
    container_name: crypton_prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=${NODE_ENV}
      - NODE_PORT=${NODE_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    command: npm run start:prod
    depends_on:
      - crypton_postgres
      - crypton_redis

  crypton_redis:
    image: redis:latest
    container_name: crypton_redis_prod

volumes:
  postgres_data_prod:
