version: '3.8'
services:
  crypton:
    container_name: crypton_prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    env_file:
      - .env.prod
    environment:
      - DB_HOST=crypton_postgres
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=crypton_redis
      - REDIS_PORT=6379
    command: npm run start:dev
    depends_on:
      - crypton_postgres
      - crypton_redis
    networks:
      - app-network

  crypton_redis:
    image: redis:latest
    container_name: crypton_redis
    command: redis-server --bind 0.0.0.0
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - app-network

  crypton_postgres:
    image: postgres:13
    container_name: crypton_postgres_prod
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data_prod:
