version: '3.8'
services:
  crypton:
    container_name: crypton_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    env_file:
      - .env.dev
    environment:
      - NODE_ENV=${NODE_ENV}
      - NODE_PORT=${NODE_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    depends_on:
      - crypton_postgres
      - crypton_redis

  crypton_redis:
    image: redis:latest
    container_name: crypton_redis_dev
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'

  crypton_postgres:
    image: postgres:13
    container_name: crypton_postgres_dev
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
