export enum NotificationType {
  FILE_REQUEST_RECEIVED = 'FILE_REQUEST_RECEIVED',
  FILE_REQUEST_APPROVED = 'FILE_REQUEST_APPROVED',
  FILE_REQUEST_REJECTED = 'FILE_REQUEST_REJECTED',
  FILE_REQUEST_CANCELED = 'FILE_REQUEST_CANCELED',
}
